name: Crypto RSS Agent

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch: # Allow manual runs
  push:
    branches: [ main ]

jobs:
  rss-agent:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Install dependencies with uv
      run: uv sync --frozen
    
    - name: Run RSS Agent
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: uv run python main.py
